# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
[project]
name = "chrony-operators-monorepo"
version = "0.1.0"
requires-python = ">=3.12"
readme = "README.md"
[dependency-groups]
fmt = [ "ruff" ]
lint = [
  "codespell",
  "jubilant==1.11.0",
  "mypy",
  "ops[testing]",
  "pep8-naming",
  "pytest",
  "pytest-asyncio",
  "requests",
  "ruff",
  "types-pyyaml",
  "types-requests",
]
integration = [
  "jubilant==1.11.0",
  "pytest",
]
[tool.uv]
package = false
[tool.codespell]
skip = "chrony-operator,chrony-client-operator"
