name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-to-edge:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@v0.0.1-alpha.9
    permissions:
      contents: write
      actions: read
    secrets: inherit
    with:
      channel: latest/edge
      integration-workflow-name: tests.yaml
