# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests
on:
  pull_request:
jobs:
  unit-tests:
    strategy:
      matrix:
        charm:
          - name: chrony
            working-directory: ./chrony-operator
          - name: chrony-client
            working-directory: ./chrony-client-operator
    name: Unit tests for ${{ matrix.charm.name }}
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
    with:
      runs-on-base: ubuntu-24.04
      python-version: "3.12"
      self-hosted-runner: false
      working-directory: ${{ matrix.charm.working-directory }}
      with-uv: true
  integration-test:
    uses: canonical/charm-ci/.github/workflows/integration-test.yml@v0.0.1-alpha.9
    with:
      spread-jobs-include: "integration-test-ci:*"
    secrets: inherit
    permissions:
      contents: read
      packages: write
      actions: read
  required_status_checks:
    name: Required Test Status Checks
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-test
    if: always() && !cancelled()
    timeout-minutes: 5
    steps:
      - name: Check all test status
        run: |
          STATUS=0
          for result in ${{ needs.unit-tests.result }} ${{ needs.integration-test.result }}; do
            if [ "$result" != "success" ] && [ "$result" != "skipped" ]; then
              echo "A test job failed with status: $result"
              STATUS=1
            fi
          done
          exit $STATUS
